[package]
name = "metrics-registry"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
itertools = "0.14.0"
prometheus = { version = "0.14.0", default-features = false }
tokio = { version = "1.47.1", features = ["full"] }